version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-automacao
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sys
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: always