// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPA.Scraping.Alura.Infra.Data.Context;

#nullable disable

namespace RPA.Scraping.Alura.Infra.Data.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20231203201208_Initial_Migration")]
    partial class Initial_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RPA.Scraping.Alura.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CargaHoraria")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("carga_horaria");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(800)")
                        .HasColumnName("descricao");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("lastupdate");

                    b.Property<string>("Professor")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("professor");

                    b.Property<string>("TermoPesquisado")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("termo_pesquisado");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.ToTable("cursos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
